# Generated by Django 4.1 on 2022-09-14 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Todolist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(blank=True)),
                ('cre_date', models.DateField(default='22-09-14')),
                ('due_date', models.DateField(default='22-09-14')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.categories')),
            ],
        ),
    ]
